### ISSUE TITLE
Fatal Error: Maximum execution time  of 120 seconds exceeded (in SSE.php:20)

### ISSUE THREAD

**Issue by jmbianca** [hhxsv5/SSE#25]
Hi,
I'm trying to use your library. So far, it working well with your example (Symfony 5.2, PHP 7.4), but, in my logs, I have this error : 
`php.CRITICAL: Fatal Error: Maximum execution time of 120 seconds exceeded {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Maximum execution time of 120 seconds exceeded at D:\\wamp\\www\\back\\vendor\\hhxsv5\\php-sse\\src\\SSE.php:20)"}`
and the PHP process is restarted (variables in code are reinitialised) but it doesn't break the stream.
How can I can avoid these errors, and especially the restarting of the process?
Thanks

**Comment by hhxsv5** [comment]
PHP SSE is actually an infinite loop, always checking whether there is new data in the loop, and flushing out if there is any. Therefore, the FPM process will run out of time, which is unavoidable. It is recommended to use the [Swoole Coroutine](https://github.com/hhxsv5/php-sse#swoole-demo) to avoid this problem.

**Comment by jmbianca** [comment]
Thank you for your answer. I eventually switch to Mercure for managing SSE since then.
